FROM public.ecr.aws/docker/library/python:3.10 as builder
COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /uvx /bin/

WORKDIR /src

COPY pyproject.toml uv.lock /src/

ENV UV_LINK_MODE=copy \
    UV_NO_INSTALLER_METADATA=1 \
    UV_COMPILE_BYTECODE=1

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-editable --group=onprem --compile-bytecode

COPY src /src/
RUN chmod +x /src/entrypoint.sh /src/main.py && \
    rm -f /src/uv.lock /src/pyproject.toml /src/requirements.txt

FROM public.ecr.aws/docker/library/python:3.10-slim

RUN apt-get update \
  && apt-get install -y wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /src /src

ENV AWS_REGION=us-east-1 \
    MODULAR_SERVICE_MODE=docker \
    PATH=/src/.venv/bin:$PATH \
    MODULAR_SDK_SERVICE_MODE=docker
WORKDIR /src
EXPOSE 8040
ENTRYPOINT ["./entrypoint.sh"]