[project]
name = "modular-service"
description = "Service that allows to manage common modular entities"
readme = "README.md"
requires-python = ">=3.14,<4"
license = {file = "LICENSE"}
version = "3.3.3"
dependencies = [
    "modular-sdk @ git+https://github.com/epam/modular-sdk@feature/python_314#egg=modular-sdk==7.1.12",
    "pydantic>=2.8,<3",
    "python-dateutil>=2.9,<3.0",
    "routes~=2.5.1",
    "typing-extensions>=4.12,<5",
]

[dependency-groups]
onprem = [
    "bcrypt>=4,<6",
    "bottle>=0.13,<1",
    "cryptography>=43,<50",
    "gunicorn>=21,<30",
    "hvac~=2.1.0",
    "jwcrypto>=1.5.6,<2",
]
test = [
    "pytest>=9",
    "pytest-cov>=6",
    "pytest-xdist>=3.6.1",
]

[tool.pyright]
pythonVersion = "3.14"
reportIncompatibleMethodOverride = "warning"
executionEnvironments = [
    {root = "src/", pythonVersion = "3.14"},
    {root = "tests/", pythonVersion = "3.14", extraPaths = ["src/"]}
]

[tool.ruff]
line-length = 79
src = ["src", "tests"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
