[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "modular-service-cli"
description = "Command line tool for modular service"
requires-python = ">=3.10,<3.15"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "click>=8.3,<9",
    "tabulate>=0.9,<1",
    "boto3>=1.26.80,<2",
    "python-dateutil>=2.9,<3",
    "modular-cli-sdk[hvac] @ git+https://github.com/epam/modular-cli-sdk@feature/python_314#egg=modular-cli-sdk==3.1.5",
]

[project.scripts]
modular-service = "modular_service_cli.group.modularservice:modularservice"

[tool.setuptools.dynamic]
version = {attr = "modular_service_cli.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["modular_service_cli*"]
namespaces = false


[tool.pyright]
include = ["modular_service_cli"]
exclude = [
    "**/__pycache__",
]
pythonVersion = "3.14"
reportIncompatibleMethodOverride = "warning"
