apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modular-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "modular-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "modular-service.chart" . }}
data:
  db-name: {{ .Values.databaseName }}