apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modular-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "modular-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "modular-service.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
    {{- end}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "modular-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "modular-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "modular-service.chart" . }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: modular-service
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: '/dev/health/live'
              scheme: HTTP
              port: 8040
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8040
              name: http
              protocol: TCP
          env:
            - name: MODULAR_SDK_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MODULAR_SDK_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MODULAR_SDK_MONGO_URI
            {{- if .Values.modularSdk.mongoUri }}
              value: "{{ .Values.modularSdk.mongoUri }}"
            {{- else }}
              value: "mongodb://$(MODULAR_SDK_MONGO_USER):$(MODULAR_SDK_MONGO_PASSWORD)@{{ .Values.mongoService }}:{{ .Values.mongoPort }}/"
            {{- end }}
            - name: MODULAR_SDK_MONGO_DB_NAME
              value: "{{ .Values.modularSdk.databaseName }}"
            - name: MODULAR_SDK_SERVICE_MODE
              value: {{ default "docker" .Values.modularSdk.serviceMode }}
            {{- if ne (default "docker" .Values.modularSdk.serviceMode) "docker" }}
            - name: MODULAR_SDK_ASSUME_ROLE_ARN
              value: {{ .Values.modularSdk.assumeRoleArn }}
            - name: MODULAR_SDK_ASSUME_ROLE_REGION
              value: {{ .Values.modularSdk.awsRegion }}
            {{- end }}
            - name: MODULAR_SDK_LOG_LEVEL
              value: {{ .Values.modularSdk.logLevel }}
            - name: MODULAR_SERVICE_SYSTEM_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: modular-service-secret
                  key: system-password
            - name: MODULAR_SDK_VAULT_URL
              value: "http://{{ .Values.vaultService }}:{{ .Values.vaultPort }}"
            - name: MODULAR_SDK_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
            - name: MODULAR_SERVICE_VAULT_ENDPOINT
              value: "http://{{ .Values.vaultService }}:{{ .Values.vaultPort }}"
            - name: MODULAR_SERVICE_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
            - name: MODULAR_SERVICE_MONGO_URI
            {{- if .Value.mongoUri }}
              value: "{{ .Values.mongoUri }}"
            {{- else }}
              value: "mongodb://$(MODULAR_SDK_MONGO_USER):$(MODULAR_SDK_MONGO_PASSWORD)@{{ .Values.mongoService }}:{{ .Values.mongoPort }}/"
            {{- end }}
            - name: MODULAR_SERVICE_MONGO_DATABASE
              value: "{{ .Values.databaseName }}"
            - name: MODULAR_SERVICE_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: HTTP_PROXY
              value: {{ .Values.httpProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.httpProxy }}
            - name: NO_PROXY
              value: {{ .Values.noProxy }}