databaseName: custodian_as_a_service
mongoUri:

service:
  type: ClusterIP
  port: 8040
  nodePort: 32104

image:
  repository: public.ecr.aws/x4s4z8e1/syndicate/modular-service
  tag: 3.3.0
  pullPolicy: Always


replicas: 1
strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

mongoService: mongo
mongoPort: 27017
vaultService: vault
vaultPort: 8200


modularSdk:
  logLevel: WARNING

  serviceMode: docker
  dbBackend: ''
  secretsBackend: ''

  # for "mongo" dbBackend
  mongoUri:
  databaseName: custodian_as_a_service

  # for "dynamo" dbBackend
  awsRegion:
  assumeRoleArn:

logLevel: INFO

httpProxy: ''
httpsProxy: ''
noProxy: 'localhost,127.0.0.1,169.254.169.254,mongo,vault,minio'