name: ci-for-tests

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  tests:
    name: Run Python tests
    needs: check_modified_files
    if: ${{ needs.check_modified_files.outputs.src_files_changes_found == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install dependencies
      run: |
        uv sync --all-extras --all-groups
    - name: Run tests with Python ${{ matrix.python-version }}
      run: |
        uv run --frozen pytest --verbose --cov=src/ --cov-report=term -n auto